#!/bin/bash
cd /usr/share/tomcat6-compiler/web
lim=$1;
gcc code.c
START=$(date +%s%N)
timeout $lim bash -c './a.out; true' <in.txt >out1.txt 2> error.txt
END=$(date +%s%N)
DIFF=$(( $END - $START ))
DIFF=$((DIFF/1000000))
echo "$DIFF" > time1.txt
echo "" > Flag.txt
